/*
 * Student Management Services
 *
 * The student management service(s) for reading student information and managing the grades. 
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * Contact: vrajesh.27@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Models;
using Data.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class ReadApiController : Controller
    {
        private readonly SMContext.SMDBContext _context;

        public ReadApiController(SMContext.SMDBContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Service for retrieving student details associated to a student id.
        /// </summary>
        /// <remarks>Retrieves student details associated to a student id.</remarks>
        /// <param name="id">The unique identifier of a student. </param>
        /// <param name="correlationID">A string identifier used for troubleshooting. * If not provided, it will be generated. </param>
        /// <response code="200">Success.</response>
        /// <response code="404">Not Found. The requested student identifer is not found.</response>
        /// <response code="500">Internal Service Error.  An unexpected error occurred.</response>
        [HttpGet]
        [Route("/student-mgmt-services/service/students/{id}")]
        [SwaggerOperation("GetStudentDetailsById")]
        [SwaggerResponse(statusCode: 200, type: typeof(Student), description: "Success.")]
        public virtual IActionResult GetStudentDetailsById([FromRoute][Required]string id, [FromHeader]string correlationID)
        { 
            StudentDataModel currentStudentDataModel = _context.Students.FirstOrDefault(student => student.ID.ToString() == id);

            return (currentStudentDataModel != null) ? (new ObjectResult(SMTranslator.TranslateStudent(currentStudentDataModel))) : new ObjectResult(StatusCode(404));
        }
    }
}
